# frozen_string_literal: true

# Generated by tools/sync-completions.py from spec/completions/. Do not edit.
module Clyops
  BASH_COMPLETION = <<'CLYOPS_BASH_TEMPLATE'
# bash completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  eval "$(__CLYOPS_PROG__ --completion bash)"
_clyops___CLYOPS_FUNC__() {
    local cur="${COMP_WORDS[COMP_CWORD]}" prev="" data rec name short type kind values rest i skip=0
    local -A otype=() okind=() ovalues=()
    local -a names=() cmds=() akind=() avalues=() aarity=()
    (( COMP_CWORD > 0 )) && prev="${COMP_WORDS[COMP_CWORD-1]}"
    # The words before the cursor let a dispatcher answer for the subcommand being typed.
    data=$("${COMP_WORDS[0]}" --bash-completion -- "${COMP_WORDS[@]:1:COMP_CWORD-1}" 2>/dev/null) || return 0
    [[ "$data" == "#clyops-completion 1"* ]] || return 0

    while IFS=$'\t' read -r rec name short type kind values rest; do
        [[ "$values" == - ]] && values=""
        case "$rec" in
            skip) skip="$name" ;;
            cmd) cmds+=("$name") ;;
            opt)
                for i in "$name" "$short"; do
                    [[ -z "$i" || "$i" == - ]] && continue
                    names+=("$i"); otype[$i]="$type"; okind[$i]="$kind"; ovalues[$i]="$values"
                done ;;
            arg)
                # arg records: name, arity, kind, values, description
                [[ "$kind" == - ]] && kind=""
                aarity+=("$short"); akind+=("$type"); avalues+=("$kind") ;;
        esac
    done <<< "$data"
    # Words up to and including a dispatched subcommand belong to the dispatcher.
    local first=$(( 1 + skip ))
    (( COMP_CWORD <= first )) && prev=""

    # Option value: --opt=VALUE (bash splits on "=") or --opt VALUE.
    local opt=""
    if [[ "$cur" == --*=* ]]; then opt="${cur%%=*}"; cur="${cur#*=}"
    elif [[ "$cur" == = && "${otype[$prev]}" == value ]]; then opt="$prev"; cur=""
    elif [[ "$prev" == = ]] && (( COMP_CWORD > first + 1 )); then opt="${COMP_WORDS[COMP_CWORD-2]}"
    elif [[ "$prev" == -* && "${otype[$prev]}" == value ]]; then opt="$prev"
    fi
    if [[ -n "$opt" ]]; then
        _clyops_value___CLYOPS_FUNC__ "${okind[$opt]}" "${ovalues[$opt]}" "$cur"
        return 0
    fi

    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${names[*]}" -- "$cur"))
        return 0
    fi

    # A dispatcher group: complete its subcommands.
    if (( ${#cmds[@]} )); then
        COMPREPLY=($(compgen -W "${cmds[*]}" -- "$cur"))
        return 0
    fi

    # A dispatched program without completion data: fall back to file names.
    if (( skip > 0 && ${#names[@]} == 0 && ${#akind[@]} == 0 )); then
        compopt -o default 2>/dev/null
        COMPREPLY=()
        return 0
    fi

    # Positional: count earlier positionals, skipping options and their values.
    local pos=0 endopts="" w
    for (( i = first; i < COMP_CWORD; i++ )); do
        w="${COMP_WORDS[i]}"
        if [[ -z "$endopts" && "$w" == -- ]]; then endopts=1
        elif [[ -z "$endopts" && "$w" == -?* ]]; then
            [[ "$w" != *=* && "${otype[$w]}" == value ]] && (( i++ ))
        elif [[ "$w" != = ]]; then (( pos++ ))
        fi
    done
    local n=${#akind[@]}
    (( n == 0 )) && return 0
    if (( pos >= n )); then
        [[ "${aarity[n-1]}" == variadic ]] || return 0
        pos=$(( n - 1 ))
    fi
    _clyops_value___CLYOPS_FUNC__ "${akind[pos]}" "${avalues[pos]}" "$cur"
}

_clyops_value___CLYOPS_FUNC__() {
    local kind="$1" values="$2" cur="$3" dir IFS=$'\n'
    case "$kind" in
        choice) COMPREPLY=($(IFS=$' \t\n'; compgen -W "${values//,/ }" -- "$cur")) ;;
        file|dir)
            local flag=-f
            [[ "$kind" == dir ]] && flag=-d
            compopt -o filenames 2>/dev/null
            COMPREPLY=($(compgen $flag -- "$cur"))
            # Bare names also match entries in the option's search dirs.
            if [[ -n "$values" && "$cur" != /* && "$cur" != ./* && "$cur" != ../* ]]; then
                local -a dirs
                IFS=: read -ra dirs <<< "$values"
                for dir in "${dirs[@]}"; do
                    [[ -d "$dir" ]] && COMPREPLY+=($(cd "$dir" && compgen $flag -- "$cur"))
                done
            fi ;;
        host) COMPREPLY=($(compgen -A hostname -- "$cur")) ;;
        none) COMPREPLY=() ;;
        *) compopt -o default 2>/dev/null; COMPREPLY=() ;;
    esac
}

complete -F _clyops___CLYOPS_FUNC__ __CLYOPS_PROG__
CLYOPS_BASH_TEMPLATE
  ZSH_COMPLETION = <<'CLYOPS_ZSH_TEMPLATE'
#compdef __CLYOPS_PROG__
# zsh completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  eval "$(__CLYOPS_PROG__ --completion zsh)"
#   or install:  __CLYOPS_PROG__ --completion zsh > "${fpath[1]}/___CLYOPS_PROG__"
_clyops___CLYOPS_FUNC__() {
    local data line esc action skip=0
    local -a f specs cmds
    # The words before the cursor let a dispatcher answer for the subcommand being typed.
    data=$("${words[1]}" --bash-completion -- "${(@)words[2,CURRENT-1]}" 2>/dev/null) || return 1
    [[ "$data" == "#clyops-completion 1"* ]] || return 1

    for line in "${(@f)data}"; do
        [[ "$line" == \#* ]] && continue
        f=("${(@ps:\t:)line}")
        if [[ "$f[1]" == skip ]]; then
            skip=$f[2]
        elif [[ "$f[1]" == cmd ]]; then
            cmds+=("${f[2]//:/\\:}:$f[3]")
        elif [[ "$f[1]" == opt ]]; then
            esc="${${${${f[7]//\\/\\\\}//\[/\\[}//\]/\\]}//:/\\:}"
            if [[ "$f[4]" == flag ]]; then
                specs+=("$f[2][$esc]")
                [[ "$f[3]" != - ]] && specs+=("$f[3][$esc]")
                continue
            fi
            action="$(_clyops_action___CLYOPS_FUNC__ "$f[5]" "$f[6]")"
            specs+=("$f[2]=[$esc]:value:$action")
            [[ "$f[3]" != - ]] && specs+=("$f[3]+[$esc]:value:$action")
        elif [[ "$f[1]" == arg ]]; then
            esc="${${f[6]//\\/\\\\}//:/\\:}"
            action="$(_clyops_action___CLYOPS_FUNC__ "$f[4]" "$f[5]")"
            if [[ "$f[3]" == variadic ]]; then specs+=("*:$esc:$action"); else specs+=(":$esc:$action"); fi
        fi
    done
    # Past a dispatched subcommand, complete its words as if they were the whole line.
    if (( skip )); then
        words=("${words[1]}" "${(@)words[2+skip,-1]}")
        (( CURRENT -= skip ))
    fi
    # A dispatcher group: complete its subcommands.
    if (( ${#cmds} )) && [[ "${words[CURRENT]}" != -* ]]; then
        _describe -t commands command cmds
        return
    fi
    # A dispatched program without completion data: fall back to file names.
    if (( skip && ${#specs} == 0 )); then
        _files
        return
    fi
    _arguments -s -S : "${specs[@]}"
}

_clyops_action___CLYOPS_FUNC__() {
    local kind="$1" values="$2"
    [[ "$values" == - ]] && values=""
    case "$kind" in
        choice) print -r -- "(${values//,/ })" ;;
        file) if [[ -n "$values" ]]; then print -r -- "{_files; _files -W \"(${values//:/ })\"}"; else print -r -- _files; fi ;;
        dir) if [[ -n "$values" ]]; then print -r -- "{_files -/; _files -/ -W \"(${values//:/ })\"}"; else print -r -- "_files -/"; fi ;;
        host) print -r -- _hosts ;;
        none) print -r -- " " ;;
        *) print -r -- _files ;;
    esac
}

if [[ "${zsh_eval_context[-1]}" == loadautofunc ]]; then
    _clyops___CLYOPS_FUNC__ "$@"
else
    compdef _clyops___CLYOPS_FUNC__ __CLYOPS_PROG__
fi
CLYOPS_ZSH_TEMPLATE
  FISH_COMPLETION = <<'CLYOPS_FISH_TEMPLATE'
# fish completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  __CLYOPS_PROG__ --completion fish | source
#   or install:  __CLYOPS_PROG__ --completion fish > ~/.config/fish/completions/__CLYOPS_PROG__.fish
function __clyops___CLYOPS_FUNC___value --argument-names kind values cur
    switch $kind
        case choice
            string split , -- $values
        case file
            __fish_complete_path $cur
            # Bare names also match entries in the option's search dirs.
            if test -n "$values"; and not string match -qr -- '^(/|\./|\.\./)' $cur
                for dir in (string split : -- $values)
                    for f in $dir/$cur*
                        string replace -- "$dir/" '' $f
                    end
                end
            end
        case dir
            __fish_complete_directories $cur
        case host
            __fish_print_hostnames
        case none
        case '*'
            __fish_complete_path $cur
    end
end

function __clyops___CLYOPS_FUNC___complete
    set -l tokens (commandline -opc)
    set -l cur (commandline -ct)
    # The words before the cursor let a dispatcher answer for the subcommand being typed.
    set -l data (command $tokens[1] --bash-completion -- $tokens[2..-1] 2>/dev/null)
    string match -q '#clyops-completion 1' -- $data[1]; or return

    set -l skip 0
    set -l cmds
    set -l onames; set -l otypes; set -l okinds; set -l ovalues; set -l odescs
    set -l akinds; set -l avalues; set -l aarity
    for line in $data[2..-1]
        set -l f (string split \t -- $line)
        switch $f[1]
            case skip
                set skip $f[2]
            case cmd
                set -a cmds "$f[2]"\t"$f[3]"
            case opt
                # "-" marks an empty field.
                set -l values $f[6]
                test "$values" = -; and set values ''
                for n in $f[2] $f[3]
                    test "$n" = -; and continue
                    set -a onames $n; set -a otypes $f[4]; set -a okinds $f[5]; set -a ovalues "$values"; set -a odescs "$f[7]"
                end
            case arg
                set -l values $f[5]
                test "$values" = -; and set values ''
                set -a aarity $f[3]; set -a akinds $f[4]; set -a avalues "$values"
        end
    end
    # Words up to and including a dispatched subcommand belong to the dispatcher.
    set -l words $tokens[(math $skip + 2)..-1]

    # --opt=VALUE
    if string match -qr -- '^--[^=]+=' $cur
        set -l opt (string replace -r '=.*' '' -- $cur)
        set -l i (contains -i -- $opt $onames)
        if test -n "$i"; and test "$otypes[$i]" = value
            for v in (__clyops___CLYOPS_FUNC___value $okinds[$i] "$ovalues[$i]" (string replace -r '^[^=]*=' '' -- $cur))
                echo "$opt=$v"
            end
        end
        return
    end
    # --opt VALUE
    if test (count $words) -gt 0
        set -l i (contains -i -- $words[-1] $onames)
        if test -n "$i"; and test "$otypes[$i]" = value
            __clyops___CLYOPS_FUNC___value $okinds[$i] "$ovalues[$i]" $cur
            return
        end
    end
    if string match -q -- '-*' $cur
        for i in (seq (count $onames))
            echo $onames[$i]\t$odescs[$i]
        end
        return
    end
    # A dispatcher group: complete its subcommands.
    if test (count $cmds) -gt 0
        printf '%s\n' $cmds
        return
    end
    # A dispatched program without completion data: fall back to file names.
    if test $skip -gt 0; and test (count $onames) -eq 0; and test (count $akinds) -eq 0
        __fish_complete_path $cur
        return
    end
    # Positional: count earlier positionals, skipping options and their values.
    set -l pos 0
    set -l skipnext 0
    set -l endopts 0
    for w in $words
        if test $skipnext -eq 1
            set skipnext 0
        else if test $endopts -eq 0; and test "$w" = --
            set endopts 1
        else if test $endopts -eq 0; and string match -q -- '-?*' $w
            set -l i (contains -i -- $w $onames)
            test -n "$i"; and test "$otypes[$i]" = value; and set skipnext 1
        else
            set pos (math $pos + 1)
        end
    end
    set -l n (count $akinds)
    test $n -eq 0; and return
    if test $pos -ge $n
        test "$aarity[$n]" = variadic; or return
        set pos (math $n - 1)
    end
    set -l k (math $pos + 1)
    __clyops___CLYOPS_FUNC___value $akinds[$k] "$avalues[$k]" $cur
end

complete -c __CLYOPS_PROG__ -f -a '(__clyops___CLYOPS_FUNC___complete)'
CLYOPS_FISH_TEMPLATE
  COMPLETION_SCRIPTS = { "bash" => BASH_COMPLETION, "zsh" => ZSH_COMPLETION, "fish" => FISH_COMPLETION }.freeze
end
