# bash completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  eval "$(__CLYOPS_PROG__ --completion bash)"
_clyops___CLYOPS_FUNC__() {
    local cur="${COMP_WORDS[COMP_CWORD]}" prev="" data rec name short type kind values rest i skip=0
    local -A otype=() okind=() ovalues=()
    local -a names=() cmds=() akind=() avalues=() aarity=()
    (( COMP_CWORD > 0 )) && prev="${COMP_WORDS[COMP_CWORD-1]}"
    # The words before the cursor let a dispatcher answer for the subcommand being typed.
    data=$("${COMP_WORDS[0]}" --bash-completion -- "${COMP_WORDS[@]:1:COMP_CWORD-1}" 2>/dev/null) || return 0
    [[ "$data" == "#clyops-completion 1"* ]] || return 0

    while IFS=$'\t' read -r rec name short type kind values rest; do
        [[ "$values" == - ]] && values=""
        case "$rec" in
            skip) skip="$name" ;;
            cmd) cmds+=("$name") ;;
            opt)
                for i in "$name" "$short"; do
                    [[ -z "$i" || "$i" == - ]] && continue
                    names+=("$i"); otype[$i]="$type"; okind[$i]="$kind"; ovalues[$i]="$values"
                done ;;
            arg)
                # arg records: name, arity, kind, values, description
                [[ "$kind" == - ]] && kind=""
                aarity+=("$short"); akind+=("$type"); avalues+=("$kind") ;;
        esac
    done <<< "$data"
    # Words up to and including a dispatched subcommand belong to the dispatcher.
    local first=$(( 1 + skip ))
    (( COMP_CWORD <= first )) && prev=""

    # Option value: --opt=VALUE (bash splits on "=") or --opt VALUE.
    local opt=""
    if [[ "$cur" == --*=* ]]; then opt="${cur%%=*}"; cur="${cur#*=}"
    elif [[ "$cur" == = && "${otype[$prev]}" == value ]]; then opt="$prev"; cur=""
    elif [[ "$prev" == = ]] && (( COMP_CWORD > first + 1 )); then opt="${COMP_WORDS[COMP_CWORD-2]}"
    elif [[ "$prev" == -* && "${otype[$prev]}" == value ]]; then opt="$prev"
    fi
    if [[ -n "$opt" ]]; then
        _clyops_value___CLYOPS_FUNC__ "${okind[$opt]}" "${ovalues[$opt]}" "$cur"
        return 0
    fi

    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${names[*]}" -- "$cur"))
        return 0
    fi

    # A dispatcher group: complete its subcommands.
    if (( ${#cmds[@]} )); then
        COMPREPLY=($(compgen -W "${cmds[*]}" -- "$cur"))
        return 0
    fi

    # A dispatched program without completion data: fall back to file names.
    if (( skip > 0 && ${#names[@]} == 0 && ${#akind[@]} == 0 )); then
        compopt -o default 2>/dev/null
        COMPREPLY=()
        return 0
    fi

    # Positional: count earlier positionals, skipping options and their values.
    local pos=0 endopts="" w
    for (( i = first; i < COMP_CWORD; i++ )); do
        w="${COMP_WORDS[i]}"
        if [[ -z "$endopts" && "$w" == -- ]]; then endopts=1
        elif [[ -z "$endopts" && "$w" == -?* ]]; then
            [[ "$w" != *=* && "${otype[$w]}" == value ]] && (( i++ ))
        elif [[ "$w" != = ]]; then (( pos++ ))
        fi
    done
    local n=${#akind[@]}
    (( n == 0 )) && return 0
    if (( pos >= n )); then
        [[ "${aarity[n-1]}" == variadic ]] || return 0
        pos=$(( n - 1 ))
    fi
    _clyops_value___CLYOPS_FUNC__ "${akind[pos]}" "${avalues[pos]}" "$cur"
}

_clyops_value___CLYOPS_FUNC__() {
    local kind="$1" values="$2" cur="$3" dir IFS=$'\n'
    case "$kind" in
        choice) COMPREPLY=($(IFS=$' \t\n'; compgen -W "${values//,/ }" -- "$cur")) ;;
        file|dir)
            local flag=-f
            [[ "$kind" == dir ]] && flag=-d
            compopt -o filenames 2>/dev/null
            COMPREPLY=($(compgen $flag -- "$cur"))
            # Bare names also match entries in the option's search dirs.
            if [[ -n "$values" && "$cur" != /* && "$cur" != ./* && "$cur" != ../* ]]; then
                local -a dirs
                IFS=: read -ra dirs <<< "$values"
                for dir in "${dirs[@]}"; do
                    [[ -d "$dir" ]] && COMPREPLY+=($(cd "$dir" && compgen $flag -- "$cur"))
                done
            fi ;;
        host) COMPREPLY=($(compgen -A hostname -- "$cur")) ;;
        none) COMPREPLY=() ;;
        *) compopt -o default 2>/dev/null; COMPREPLY=() ;;
    esac
}

complete -F _clyops___CLYOPS_FUNC__ __CLYOPS_PROG__
