#compdef __CLYOPS_PROG__
# zsh completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  eval "$(__CLYOPS_PROG__ --completion zsh)"
#   or install:  __CLYOPS_PROG__ --completion zsh > "${fpath[1]}/___CLYOPS_PROG__"
_clyops___CLYOPS_FUNC__() {
    local data line esc action
    local -a f specs
    data=$("${words[1]}" --bash-completion 2>/dev/null) || return 1
    [[ "$data" == "#clyops-completion 1"* ]] || return 1

    for line in "${(@f)data}"; do
        [[ "$line" == \#* ]] && continue
        f=("${(@ps:\t:)line}")
        if [[ "$f[1]" == opt ]]; then
            esc="${${${${f[7]//\\/\\\\}//\[/\\[}//\]/\\]}//:/\\:}"
            if [[ "$f[4]" == flag ]]; then
                specs+=("$f[2][$esc]")
                [[ "$f[3]" != - ]] && specs+=("$f[3][$esc]")
                continue
            fi
            action="$(_clyops_action___CLYOPS_FUNC__ "$f[5]" "$f[6]")"
            specs+=("$f[2]=[$esc]:value:$action")
            [[ "$f[3]" != - ]] && specs+=("$f[3]+[$esc]:value:$action")
        elif [[ "$f[1]" == arg ]]; then
            esc="${${f[6]//\\/\\\\}//:/\\:}"
            action="$(_clyops_action___CLYOPS_FUNC__ "$f[4]" "$f[5]")"
            if [[ "$f[3]" == variadic ]]; then specs+=("*:$esc:$action"); else specs+=(":$esc:$action"); fi
        fi
    done
    _arguments -s -S : "${specs[@]}"
}

_clyops_action___CLYOPS_FUNC__() {
    local kind="$1" values="$2"
    [[ "$values" == - ]] && values=""
    case "$kind" in
        choice) print -r -- "(${values//,/ })" ;;
        file) if [[ -n "$values" ]]; then print -r -- "{_files; _files -W \"(${values//:/ })\"}"; else print -r -- _files; fi ;;
        dir) if [[ -n "$values" ]]; then print -r -- "{_files -/; _files -/ -W \"(${values//:/ })\"}"; else print -r -- "_files -/"; fi ;;
        host) print -r -- _hosts ;;
        none) print -r -- " " ;;
        *) print -r -- _files ;;
    esac
}

if [[ "${zsh_eval_context[-1]}" == loadautofunc ]]; then
    _clyops___CLYOPS_FUNC__ "$@"
else
    compdef _clyops___CLYOPS_FUNC__ __CLYOPS_PROG__
fi
