#!/usr/bin/env python3
"""Embed spec/completions/* into every package so each library is self-contained.

    python3 tools/sync-completions.py          # rewrite the generated files
    python3 tools/sync-completions.py --check  # exit 1 if any are stale (CI)
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHELLS = ("bash", "zsh", "fish")
HEADER = "Generated by tools/sync-completions.py from spec/completions/. Do not edit."


def load():
    out = {}
    for shell in SHELLS:
        with open(os.path.join(ROOT, "spec", "completions", f"clyops.{shell}")) as fh:
            out[shell] = fh.read()
    return out


def c_lines(text):
    # One literal per line, NULL-terminated: a single literal would exceed the
    # 4095 characters ISO C requires compilers to support.
    lines = []
    for line in text.splitlines(True):
        esc = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t").replace("\n", "\\n")
        lines.append(f'    "{esc}",')
    return "\n".join(lines + ["    NULL"])


def ansi_c(text):
    return "$'" + text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\t", "\\t") + "'"


def outputs(scripts):
    files = {}
    files["packages/js/src/completions.ts"] = (
        f"// {HEADER}\n"
        "export const COMPLETION_SCRIPTS: Record<string, string> = {\n"
        + "".join(f"  {s}: {json.dumps(scripts[s])},\n" for s in SHELLS)
        + "};\n"
    )
    files["packages/python/src/clyops/_completions.py"] = (
        f"# {HEADER}\n"
        "SCRIPTS = {\n" + "".join(f"    {s!r}: {scripts[s]!r},\n" for s in SHELLS) + "}\n"
    )
    rust = f"// {HEADER}\n"
    for s in SHELLS:
        hashes = "#" * 3
        rust += f'pub(crate) const {s.upper()}: &str = r{hashes}"{scripts[s]}"{hashes};\n'
    files["packages/rust/src/completions.rs"] = rust
    c = f"/* {HEADER} */\n#ifndef CLYOPS_COMPLETIONS_H\n#define CLYOPS_COMPLETIONS_H\n\n"
    for s in SHELLS:
        c += f"static const char* const CLYOPS_COMPLETION_{s.upper()}[] = {{\n{c_lines(scripts[s])}\n}};\n\n"
    files["packages/c/src/completions.h"] = c + "#endif\n"
    files["packages/go/completions.go"] = (
        f"// Code generated by tools/sync-completions.py from spec/completions/. DO NOT EDIT.\n\n"
        "package clyops\n\n"
        "var completionScripts = map[string]string{\n"
        + "".join(f"\t{(json.dumps(s) + ':').ljust(7)} {json.dumps(scripts[s])},\n" for s in SHELLS)
        + "}\n"
    )
    return files


BASH_BEGIN = "# BEGIN GENERATED COMPLETIONS"
BASH_END = "# END GENERATED COMPLETIONS"


def bash_lib(scripts):
    path = os.path.join(ROOT, "packages", "bash", "clyops.sh")
    with open(path) as fh:
        text = fh.read()
    block = f"{BASH_BEGIN} ({HEADER})\n"
    for s in SHELLS:
        block += f"_CLYOPS_COMPLETION_{s.upper()}={ansi_c(scripts[s])}\n"
    block += BASH_END
    pattern = re.compile(re.escape(BASH_BEGIN) + r".*?" + re.escape(BASH_END), re.S)
    if not pattern.search(text):
        sys.exit(f"{path}: missing {BASH_BEGIN} / {BASH_END} markers")
    return path, pattern.sub(lambda _: block, text)


def main():
    check = "--check" in sys.argv
    scripts = load()
    files = {os.path.join(ROOT, k): v for k, v in outputs(scripts).items()}
    path, text = bash_lib(scripts)
    files[path] = text
    stale = []
    for path, content in files.items():
        current = open(path).read() if os.path.exists(path) else None
        if current != content:
            stale.append(os.path.relpath(path, ROOT))
            if not check:
                with open(path, "w") as fh:
                    fh.write(content)
    if check and stale:
        print("stale generated completion files (run tools/sync-completions.py):\n  " + "\n  ".join(stale))
        return 1
    print(("up to date" if not stale else "updated: " + ", ".join(stale)) if not check else "up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
