# fish completion for demo (generated by clyops)
# Enable with:  demo --completion fish | source
#   or install:  demo --completion fish > ~/.config/fish/completions/demo.fish
function __clyops_demo_positional --argument-names n
    # True when the token being completed is positional argument n (1-based).
    set -l count 0
    set -l skip 0
    for tok in (commandline -opc)[2..-1]
        if test $skip -eq 1
            set skip 0
        else if string match -qr -- '^-' $tok
            contains -- (string replace -r '=.*' '' -- $tok) $__clyops_demo_value_opts; and not string match -q -- '*=*' $tok; and set skip 1
        else
            set count (math $count + 1)
        end
    end
    test $count -eq (math $n - 1); or begin; test "$argv[2]" = variadic; and test $count -ge (math $n - 1); end
end

set -g __clyops_demo_value_opts
set -l __clyops_pos 0
for line in (command demo --bash-completion 2>/dev/null)
    set -l f (string split \t -- $line)
    switch $f[1]
        case opt
            set -l args -c demo -l (string replace -r '^--' '' -- $f[2]) -d $f[7]
            test $f[3] != -; and set -a args -s (string sub -s 2 -- $f[3])
            if test $f[4] = value
                set -a __clyops_demo_value_opts $f[2]
                test $f[3] != -; and set -a __clyops_demo_value_opts $f[3]
                set -a args -r
                switch $f[5]
                    case choice
                        set -a args -f -a (string replace -a , ' ' -- $f[6])
                    case dir
                        set -a args -f -a '(__fish_complete_directories)'
                    case host
                        set -a args -f -a '(__fish_print_hostnames)'
                    case none
                        set -a args -f
                end
            end
            complete $args
        case arg
            set __clyops_pos (math $__clyops_pos + 1)
            set -l cond "__clyops_demo_positional $__clyops_pos $f[3]"
            switch $f[4]
                case choice
                    complete -c demo -f -n $cond -a (string replace -a , ' ' -- $f[5]) -d $f[6]
                case dir
                    complete -c demo -f -n $cond -a '(__fish_complete_directories)' -d $f[6]
                case host
                    complete -c demo -f -n $cond -a '(__fish_print_hostnames)' -d $f[6]
                case none
                    complete -c demo -f -n $cond
            end
    end
end
