# fish completion for demo (generated by clyops)
# Enable with:  demo --completion fish | source
#   or install:  demo --completion fish > ~/.config/fish/completions/demo.fish
function __clyops_demo_value --argument-names kind values cur
    switch $kind
        case choice
            string split , -- $values
        case file
            __fish_complete_path $cur
            # Bare names also match entries in the option's search dirs.
            if test -n "$values"; and not string match -qr -- '^(/|\./|\.\./)' $cur
                for dir in (string split : -- $values)
                    for f in $dir/$cur*
                        string replace -- "$dir/" '' $f
                    end
                end
            end
        case dir
            __fish_complete_directories $cur
        case host
            __fish_print_hostnames
        case none
        case '*'
            __fish_complete_path $cur
    end
end

function __clyops_demo_complete
    set -l tokens (commandline -opc)
    set -l cur (commandline -ct)
    # The words before the cursor let a dispatcher answer for the subcommand being typed.
    set -l data (command $tokens[1] --bash-completion -- $tokens[2..-1] 2>/dev/null)
    string match -q '#clyops-completion 1' -- $data[1]; or return

    set -l skip 0
    set -l cmds
    set -l onames; set -l otypes; set -l okinds; set -l ovalues; set -l odescs
    set -l akinds; set -l avalues; set -l aarity
    for line in $data[2..-1]
        set -l f (string split \t -- $line)
        switch $f[1]
            case skip
                set skip $f[2]
            case cmd
                set -a cmds "$f[2]"\t"$f[3]"
            case opt
                # "-" marks an empty field.
                set -l values $f[6]
                test "$values" = -; and set values ''
                for n in $f[2] $f[3]
                    test "$n" = -; and continue
                    set -a onames $n; set -a otypes $f[4]; set -a okinds $f[5]; set -a ovalues "$values"; set -a odescs "$f[7]"
                end
            case arg
                set -l values $f[5]
                test "$values" = -; and set values ''
                set -a aarity $f[3]; set -a akinds $f[4]; set -a avalues "$values"
        end
    end
    # Words up to and including a dispatched subcommand belong to the dispatcher.
    set -l words $tokens[(math $skip + 2)..-1]

    # --opt=VALUE
    if string match -qr -- '^--[^=]+=' $cur
        set -l opt (string replace -r '=.*' '' -- $cur)
        set -l i (contains -i -- $opt $onames)
        if test -n "$i"; and test "$otypes[$i]" = value
            for v in (__clyops_demo_value $okinds[$i] "$ovalues[$i]" (string replace -r '^[^=]*=' '' -- $cur))
                echo "$opt=$v"
            end
        end
        return
    end
    # --opt VALUE
    if test (count $words) -gt 0
        set -l i (contains -i -- $words[-1] $onames)
        if test -n "$i"; and test "$otypes[$i]" = value
            __clyops_demo_value $okinds[$i] "$ovalues[$i]" $cur
            return
        end
    end
    if string match -q -- '-*' $cur
        for i in (seq (count $onames))
            echo $onames[$i]\t$odescs[$i]
        end
        return
    end
    # A dispatcher group: complete its subcommands.
    if test (count $cmds) -gt 0
        printf '%s\n' $cmds
        return
    end
    # A dispatched program without completion data: fall back to file names.
    if test $skip -gt 0; and test (count $onames) -eq 0; and test (count $akinds) -eq 0
        __fish_complete_path $cur
        return
    end
    # Positional: count earlier positionals, skipping options and their values.
    set -l pos 0
    set -l skipnext 0
    set -l endopts 0
    for w in $words
        if test $skipnext -eq 1
            set skipnext 0
        else if test $endopts -eq 0; and test "$w" = --
            set endopts 1
        else if test $endopts -eq 0; and string match -q -- '-?*' $w
            set -l i (contains -i -- $w $onames)
            test -n "$i"; and test "$otypes[$i]" = value; and set skipnext 1
        else
            set pos (math $pos + 1)
        end
    end
    set -l n (count $akinds)
    test $n -eq 0; and return
    if test $pos -ge $n
        test "$aarity[$n]" = variadic; or return
        set pos (math $n - 1)
    end
    set -l k (math $pos + 1)
    __clyops_demo_value $akinds[$k] "$avalues[$k]" $cur
end

complete -c demo -f -a '(__clyops_demo_complete)'
