// Generated by tools/sync-completions.py from spec/completions/. Do not edit.
pub(crate) const BASH: &str = r###"# bash completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  eval "$(__CLYOPS_PROG__ --completion bash)"
_clyops___CLYOPS_FUNC__() {
    local cur="${COMP_WORDS[COMP_CWORD]}" prev="" data rec name short type kind values rest i
    local -A otype=() okind=() ovalues=()
    local -a names=() akind=() avalues=() aarity=()
    (( COMP_CWORD > 0 )) && prev="${COMP_WORDS[COMP_CWORD-1]}"
    data=$("${COMP_WORDS[0]}" --bash-completion 2>/dev/null) || return 0
    [[ "$data" == "#clyops-completion 1"* ]] || return 0

    while IFS=$'\t' read -r rec name short type kind values rest; do
        [[ "$values" == - ]] && values=""
        case "$rec" in
            opt)
                for i in "$name" "$short"; do
                    [[ -z "$i" || "$i" == - ]] && continue
                    names+=("$i"); otype[$i]="$type"; okind[$i]="$kind"; ovalues[$i]="$values"
                done ;;
            arg)
                # arg records: name, arity, kind, values, description
                [[ "$kind" == - ]] && kind=""
                aarity+=("$short"); akind+=("$type"); avalues+=("$kind") ;;
        esac
    done <<< "$data"

    # Option value: --opt=VALUE (bash splits on "=") or --opt VALUE.
    local opt=""
    if [[ "$cur" == --*=* ]]; then opt="${cur%%=*}"; cur="${cur#*=}"
    elif [[ "$cur" == = && "${otype[$prev]}" == value ]]; then opt="$prev"; cur=""
    elif [[ "$prev" == = ]] && (( COMP_CWORD > 1 )); then opt="${COMP_WORDS[COMP_CWORD-2]}"
    elif [[ "$prev" == -* && "${otype[$prev]}" == value ]]; then opt="$prev"
    fi
    if [[ -n "$opt" ]]; then
        _clyops_value___CLYOPS_FUNC__ "${okind[$opt]}" "${ovalues[$opt]}" "$cur"
        return 0
    fi

    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${names[*]}" -- "$cur"))
        return 0
    fi

    # Positional: count earlier positionals, skipping options and their values.
    local pos=0 endopts="" w
    for (( i = 1; i < COMP_CWORD; i++ )); do
        w="${COMP_WORDS[i]}"
        if [[ -z "$endopts" && "$w" == -- ]]; then endopts=1
        elif [[ -z "$endopts" && "$w" == -?* ]]; then
            [[ "$w" != *=* && "${otype[$w]}" == value ]] && (( i++ ))
        elif [[ "$w" != = ]]; then (( pos++ ))
        fi
    done
    local n=${#akind[@]}
    (( n == 0 )) && return 0
    if (( pos >= n )); then
        [[ "${aarity[n-1]}" == variadic ]] || return 0
        pos=$(( n - 1 ))
    fi
    _clyops_value___CLYOPS_FUNC__ "${akind[pos]}" "${avalues[pos]}" "$cur"
}

_clyops_value___CLYOPS_FUNC__() {
    local kind="$1" values="$2" cur="$3" dir IFS=$'\n'
    case "$kind" in
        choice) COMPREPLY=($(IFS=$' \t\n'; compgen -W "${values//,/ }" -- "$cur")) ;;
        file|dir)
            local flag=-f
            [[ "$kind" == dir ]] && flag=-d
            compopt -o filenames 2>/dev/null
            COMPREPLY=($(compgen $flag -- "$cur"))
            # Bare names also match entries in the option's search dirs.
            if [[ -n "$values" && "$cur" != /* && "$cur" != ./* && "$cur" != ../* ]]; then
                local -a dirs
                IFS=: read -ra dirs <<< "$values"
                for dir in "${dirs[@]}"; do
                    [[ -d "$dir" ]] && COMPREPLY+=($(cd "$dir" && compgen $flag -- "$cur"))
                done
            fi ;;
        host) COMPREPLY=($(compgen -A hostname -- "$cur")) ;;
        none) COMPREPLY=() ;;
        *) compopt -o default 2>/dev/null; COMPREPLY=() ;;
    esac
}

complete -F _clyops___CLYOPS_FUNC__ __CLYOPS_PROG__
"###;
pub(crate) const ZSH: &str = r###"#compdef __CLYOPS_PROG__
# zsh completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  eval "$(__CLYOPS_PROG__ --completion zsh)"
#   or install:  __CLYOPS_PROG__ --completion zsh > "${fpath[1]}/___CLYOPS_PROG__"
_clyops___CLYOPS_FUNC__() {
    local data line esc action
    local -a f specs
    data=$("${words[1]}" --bash-completion 2>/dev/null) || return 1
    [[ "$data" == "#clyops-completion 1"* ]] || return 1

    for line in "${(@f)data}"; do
        [[ "$line" == \#* ]] && continue
        f=("${(@ps:\t:)line}")
        if [[ "$f[1]" == opt ]]; then
            esc="${${${${f[7]//\\/\\\\}//\[/\\[}//\]/\\]}//:/\\:}"
            if [[ "$f[4]" == flag ]]; then
                specs+=("$f[2][$esc]")
                [[ "$f[3]" != - ]] && specs+=("$f[3][$esc]")
                continue
            fi
            action="$(_clyops_action___CLYOPS_FUNC__ "$f[5]" "$f[6]")"
            specs+=("$f[2]=[$esc]:value:$action")
            [[ "$f[3]" != - ]] && specs+=("$f[3]+[$esc]:value:$action")
        elif [[ "$f[1]" == arg ]]; then
            esc="${${f[6]//\\/\\\\}//:/\\:}"
            action="$(_clyops_action___CLYOPS_FUNC__ "$f[4]" "$f[5]")"
            if [[ "$f[3]" == variadic ]]; then specs+=("*:$esc:$action"); else specs+=(":$esc:$action"); fi
        fi
    done
    _arguments -s -S : "${specs[@]}"
}

_clyops_action___CLYOPS_FUNC__() {
    local kind="$1" values="$2"
    [[ "$values" == - ]] && values=""
    case "$kind" in
        choice) print -r -- "(${values//,/ })" ;;
        file) if [[ -n "$values" ]]; then print -r -- "{_files; _files -W \"(${values//:/ })\"}"; else print -r -- _files; fi ;;
        dir) if [[ -n "$values" ]]; then print -r -- "{_files -/; _files -/ -W \"(${values//:/ })\"}"; else print -r -- "_files -/"; fi ;;
        host) print -r -- _hosts ;;
        none) print -r -- " " ;;
        *) print -r -- _files ;;
    esac
}

if [[ "${zsh_eval_context[-1]}" == loadautofunc ]]; then
    _clyops___CLYOPS_FUNC__ "$@"
else
    compdef _clyops___CLYOPS_FUNC__ __CLYOPS_PROG__
fi
"###;
pub(crate) const FISH: &str = r###"# fish completion for __CLYOPS_PROG__ (generated by clyops)
# Enable with:  __CLYOPS_PROG__ --completion fish | source
#   or install:  __CLYOPS_PROG__ --completion fish > ~/.config/fish/completions/__CLYOPS_PROG__.fish
function __clyops___CLYOPS_FUNC___positional --argument-names n
    # True when the token being completed is positional argument n (1-based).
    set -l count 0
    set -l skip 0
    for tok in (commandline -opc)[2..-1]
        if test $skip -eq 1
            set skip 0
        else if string match -qr -- '^-' $tok
            contains -- (string replace -r '=.*' '' -- $tok) $__clyops___CLYOPS_FUNC___value_opts; and not string match -q -- '*=*' $tok; and set skip 1
        else
            set count (math $count + 1)
        end
    end
    test $count -eq (math $n - 1); or begin; test "$argv[2]" = variadic; and test $count -ge (math $n - 1); end
end

set -g __clyops___CLYOPS_FUNC___value_opts
set -l __clyops_pos 0
for line in (command __CLYOPS_PROG__ --bash-completion 2>/dev/null)
    set -l f (string split \t -- $line)
    switch $f[1]
        case opt
            set -l args -c __CLYOPS_PROG__ -l (string replace -r '^--' '' -- $f[2]) -d $f[7]
            test $f[3] != -; and set -a args -s (string sub -s 2 -- $f[3])
            if test $f[4] = value
                set -a __clyops___CLYOPS_FUNC___value_opts $f[2]
                test $f[3] != -; and set -a __clyops___CLYOPS_FUNC___value_opts $f[3]
                set -a args -r
                switch $f[5]
                    case choice
                        set -a args -f -a (string replace -a , ' ' -- $f[6])
                    case dir
                        set -a args -f -a '(__fish_complete_directories)'
                    case host
                        set -a args -f -a '(__fish_print_hostnames)'
                    case none
                        set -a args -f
                end
            end
            complete $args
        case arg
            set __clyops_pos (math $__clyops_pos + 1)
            set -l cond "__clyops___CLYOPS_FUNC___positional $__clyops_pos $f[3]"
            switch $f[4]
                case choice
                    complete -c __CLYOPS_PROG__ -f -n $cond -a (string replace -a , ' ' -- $f[5]) -d $f[6]
                case dir
                    complete -c __CLYOPS_PROG__ -f -n $cond -a '(__fish_complete_directories)' -d $f[6]
                case host
                    complete -c __CLYOPS_PROG__ -f -n $cond -a '(__fish_print_hostnames)' -d $f[6]
                case none
                    complete -c __CLYOPS_PROG__ -f -n $cond
            end
    end
end
"###;
