// Generated by tools/bundle-js.mjs from packages/tools/src/index.ts. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// packages/tools/src/index.ts
var index_exports = {};
__export(index_exports, {
  InputError: () => InputError,
  allowed: () => allowed,
  auditLog: () => auditLog,
  checkWithin: () => checkWithin,
  classify: () => classify,
  commandName: () => commandName,
  commands: () => commands,
  discover: () => discover,
  expandCommands: () => expandCommands,
  inputKey: () => inputKey,
  inputKeys: () => inputKeys,
  isBareFlag: () => isBareFlag,
  isPathValued: () => isPathValued,
  isTextType: () => isTextType,
  loadSchema: () => loadSchema,
  loadTools: () => loadTools,
  readSettings: () => readSettings,
  redactArgv: () => redactArgv,
  run: () => run,
  runTool: () => runTool,
  shellQuote: () => shellQuote,
  stamp: () => stamp,
  start: () => start,
  startTool: () => startTool,
  tail: () => tail,
  toArgv: () => toArgv,
  toJsonSchema: () => toJsonSchema,
  valueSchema: () => valueSchema,
  watchTools: () => watchTools
});
module.exports = __toCommonJS(index_exports);

// packages/tools/src/schema.ts
var import_node_child_process = require("node:child_process");
var import_node_fs = require("node:fs");

// packages/tools/src/detection.ts
function usesClyops(source) {
  if (!source.startsWith("#!") && source.includes("\0")) return source.includes("#clyops-completion");
  const tokens = [];
  let line = 1;
  let first = true;
  let i = 0;
  let heredoc;
  while (i < source.length) {
    const c = source[i];
    if (c === "\n") {
      i++;
      line++;
      first = true;
      if (heredoc) {
        while (i < source.length) {
          const end = source.indexOf("\n", i);
          const next = end < 0 ? source.length : end + 1;
          const done = source.slice(i, end < 0 ? next : end).trim() === heredoc;
          i = next;
          line++;
          if (done) break;
        }
        heredoc = void 0;
      }
      continue;
    }
    if (/\s/.test(c)) {
      i++;
      continue;
    }
    if (c === "#" || source.startsWith("//", i)) {
      const end = source.indexOf("\n", i);
      const comment = source.slice(i, end < 0 ? source.length : end).trim();
      if (first && line <= 10 && /^(#|\/\/)\s*clyops-tool$/.test(comment)) return true;
      i = end < 0 ? source.length : end;
      continue;
    }
    if (source.startsWith("/*", i)) {
      const end = source.indexOf("*/", i + 2);
      const next = end < 0 ? source.length : end + 2;
      line += (source.slice(i, next).match(/\n/g) ?? []).length;
      i = next;
      first = false;
      continue;
    }
    const start2 = i;
    const tokenLine = line;
    const tokenFirst = first;
    let literal = false;
    let value;
    if (c === "'" || c === '"' || c === "`") {
      literal = true;
      const quote = source.startsWith(c.repeat(3), i) ? c.repeat(3) : c;
      i += quote.length;
      const content = i;
      while (i < source.length && !source.startsWith(quote, i)) {
        if (source[i] === "\\") i++;
        i++;
      }
      value = source.slice(content, i);
      i = Math.min(source.length, i + quote.length);
      if (quote.length === 3 || c === "`") value = "";
      line += (source.slice(start2, i).match(/\n/g) ?? []).length;
    } else if (/[A-Za-z0-9_$-]/.test(c)) {
      while (i < source.length && /[A-Za-z0-9_$-]/.test(source[i])) i++;
      value = source.slice(start2, i);
    } else {
      value = c;
      i++;
    }
    tokens.push({ value, literal, line: tokenLine, first: tokenFirst, start: start2, end: i });
    first = false;
    const n = tokens.length;
    if (n >= 3 && tokens[n - 3].value === "<" && tokens[n - 2].value === "<") heredoc = value;
    if (n >= 4 && tokens[n - 4].value === "<" && tokens[n - 3].value === "<" && tokens[n - 2].value === "-") heredoc = value;
  }
  const module2 = (t) => t?.literal && !t.value.includes("\n") && /^(clyops(?:[-/].*)?|.*\/clyops\.(?:cjs|mjs|js|ts))$/.test(t.value);
  for (let n = 0; n < tokens.length; n++) {
    const t = tokens[n];
    if (t.literal) continue;
    const next = tokens[n + 1];
    if (t.first && (t.value === "source" || t.value === ".") && next?.line === t.line) {
      let path = next.value;
      let end = next.end;
      for (let j = n + 2; j < tokens.length && tokens[j].start === end; j++) {
        path += tokens[j].value;
        end = tokens[j].end;
      }
      if (/(^|\/)clyops\.sh$/.test(path)) return true;
    }
    if (t.first && (t.value === "import" || t.value === "from") && next?.value === "clyops" && !next.literal) return true;
    if (!t.literal && t.value === "require" && tokens[n - 1]?.value !== "." && next?.value === "(" && module2(tokens[n + 2]) && tokens[n + 3]?.value === ")") return true;
    if (t.first && t.value === "import") {
      if (module2(next)) return true;
      for (let j = n + 1; j < tokens.length && tokens[j].value !== ";"; j++) {
        if (!tokens[j].literal && tokens[j].value === "from" && module2(tokens[j + 1])) return true;
        if (tokens[j].first && ["import", "const", "let", "var", "function"].includes(tokens[j].value)) break;
      }
    }
  }
  return false;
}

// packages/tools/src/schema.ts
function classify(file) {
  let text;
  try {
    text = (0, import_node_fs.readFileSync)(file, "latin1");
  } catch {
    return "other";
  }
  const firstLine = text.slice(0, text.indexOf("\n") >>> 0);
  if (firstLine.startsWith("#!") && firstLine.includes("clyops-dispatch")) return "dispatcher";
  return usesClyops(text) ? "tool" : "other";
}
function stamp(file) {
  const s = (0, import_node_fs.statSync)(file);
  return `${s.mtimeMs}:${s.size}`;
}
var cache = /* @__PURE__ */ new Map();
function loadSchema(file, opts = {}) {
  const key = stamp(file);
  const hit = cache.get(file);
  if (hit && hit.stamp === key) return hit.schema;
  const schema = new Promise((resolve3, reject) => {
    (0, import_node_child_process.execFile)(file, ["--help-json-schema"], { cwd: opts.cwd, timeout: opts.timeoutMs ?? 5e3, maxBuffer: 16 << 20 }, (err, stdout) => {
      if (err) return reject(new Error(`${file} does not provide --help-json-schema: ${err.message}`));
      const start2 = stdout.indexOf("{");
      const end = stdout.lastIndexOf("}");
      if (start2 < 0 || end < start2) return reject(new Error(`${file} produced no JSON schema`));
      try {
        const parsed = JSON.parse(stdout.slice(start2, end + 1));
        if (parsed.clyops !== 1 || !Array.isArray(parsed.options) || !Array.isArray(parsed.arguments) || typeof parsed.description !== "string") {
          throw new Error("expected a clyops: 1 schema with description, options and arguments");
        }
        resolve3(parsed);
      } catch (e) {
        reject(new Error(`${file}: invalid JSON schema: ${e.message}`));
      }
    });
  });
  schema.catch(() => cache.delete(file));
  cache.set(file, { stamp: key, schema });
  return schema;
}

// packages/tools/src/discover.ts
var import_node_fs2 = require("node:fs");
var import_node_path = require("node:path");
function readSettings(file, allowDir) {
  const settings = { description: "", ignore: [] };
  (0, import_node_fs2.readFileSync)(file, "utf8").split("\n").forEach((raw, n) => {
    const line = raw.trim();
    if (!line || line.startsWith("#")) return;
    const colon = line.indexOf(":");
    if (colon < 0) throw new Error(`${file}:${n + 1}: expected 'key: value'`);
    const key = line.slice(0, colon).trim();
    const value = line.slice(colon + 1).trim();
    if (key === "description") settings.description = value;
    else if (key === "ignore") settings.ignore = value.split(",").map((s) => s.trim()).filter(Boolean);
    else if (key === "allow" || key === "deny") settings[key] = value.split(",").map((s) => s.trim()).filter(Boolean);
    else if (key === "dir" && allowDir) settings.dir = value;
    else throw new Error(`${file}:${n + 1}: unknown key '${key}'`);
  });
  return settings;
}
function isExecutable(file) {
  const s = (0, import_node_fs2.statSync)(file);
  if (!s.isFile()) return false;
  if (process.platform !== "win32") return (s.mode & 73) !== 0;
  const exts = (process.env.PATHEXT || ".EXE;.BAT;.CMD;.COM").toLowerCase().split(";");
  const dot = file.lastIndexOf(".");
  return dot > 0 && exts.includes(file.slice(dot).toLowerCase());
}
function commandName(fileName) {
  const dot = fileName.lastIndexOf(".");
  return dot > 0 ? fileName.slice(0, dot) : fileName;
}
function discover(root, opts = {}) {
  const real = (0, import_node_fs2.realpathSync)((0, import_node_path.resolve)(root));
  if ((0, import_node_fs2.statSync)(real).isFile()) {
    const settings2 = readSettings(real, true);
    const dir = (0, import_node_path.resolve)((0, import_node_path.dirname)(real), settings2.dir ?? ".");
    return { ...walk(dir, opts.name ?? (0, import_node_path.basename)(root), [], settings2, /* @__PURE__ */ new Set([real])), allow: settings2.allow, deny: settings2.deny };
  }
  const file = (0, import_node_path.join)(real, ".clyops");
  const settings = exists(file) ? readSettings(file, false) : { description: "", ignore: [] };
  return { ...walk(real, opts.name ?? (0, import_node_path.basename)(real), [], settings, /* @__PURE__ */ new Set()), allow: settings.allow, deny: settings.deny };
}
function exists(file) {
  try {
    return (0, import_node_fs2.statSync)(file).isFile();
  } catch {
    return false;
  }
}
function walk(dir, name, words, settings, above) {
  const skip = /* @__PURE__ */ new Set([...above, dir]);
  const group = { name, words, dir, description: settings.description, groups: [], commands: [] };
  const byName = /* @__PURE__ */ new Map();
  for (const fileName of (0, import_node_fs2.readdirSync)(dir).filter((f) => !f.startsWith(".")).sort()) {
    const entry = commandName(fileName);
    if (settings.ignore.includes(fileName) || settings.ignore.includes(entry)) continue;
    const path = (0, import_node_path.join)(dir, fileName);
    let isDir;
    try {
      isDir = (0, import_node_fs2.statSync)(path).isDirectory();
    } catch {
      continue;
    }
    if (isDir) {
      const file = (0, import_node_path.join)(path, ".clyops");
      const sub = walk(path, fileName, [...words, fileName], exists(file) ? readSettings(file, false) : { description: "", ignore: [] }, skip);
      if (sub.groups.length || sub.commands.length) byName.set(fileName, sub);
      continue;
    }
    if (byName.has(entry) || !isExecutable(path)) continue;
    const real = (0, import_node_fs2.realpathSync)(path);
    if (skip.has(real)) continue;
    const kind = classify(path);
    const nested = kind === "dispatcher" ? readSettings(real, true) : void 0;
    const target = nested && (0, import_node_fs2.realpathSync)((0, import_node_path.resolve)((0, import_node_path.dirname)(real), nested.dir ?? "."));
    if (nested && target && !skip.has(target)) {
      const sub = walk(target, entry, [...words, entry], nested, /* @__PURE__ */ new Set([...skip, real]));
      if (sub.groups.length || sub.commands.length) byName.set(entry, sub);
    } else {
      byName.set(entry, { name: entry, words: [...words, entry], file: path, kind });
    }
  }
  for (const key of [...byName.keys()].sort()) {
    const entry = byName.get(key);
    if ("dir" in entry) group.groups.push(entry);
    else group.commands.push(entry);
  }
  return group;
}
function commands(group) {
  return [...group.commands, ...group.groups.flatMap(commands)];
}

// packages/tools/src/argv.ts
var import_node_fs3 = require("node:fs");
var import_node_path2 = require("node:path");
var InputError = class extends Error {
  status = 400;
};
function inputKey(name) {
  return name.replace(/-/g, "_");
}
function inputKeys(item) {
  const variable = "variableName" in item ? item.variableName : item.name;
  return [.../* @__PURE__ */ new Set([inputKey(item.name), item.name, variable.toLowerCase()])].filter(Boolean);
}
function isBareFlag(option) {
  const choices = [...option.choices].sort().join(",");
  return option.isFlag && choices !== "false,true";
}
function isPathValued(validation, type) {
  return type === "path" || validation === "path" || validation.startsWith("file:") || validation.startsWith("dir:");
}
var TRUE = /^(true|1|yes|on)$/i;
function toArgv(schema, input, opts = {}) {
  const used = /* @__PURE__ */ new Set();
  const out = { argv: [], env: {}, unknown: [], controlled: [] };
  const pick = (item) => {
    for (const key of inputKeys(item)) {
      if (Object.prototype.hasOwnProperty.call(input, key)) {
        used.add(key);
        return { key, value: input[key] };
      }
    }
    return void 0;
  };
  const text = (value, pathValued, name = "") => {
    let s = typeof value === "object" ? JSON.stringify(value) : String(value);
    if (opts.render) s = opts.render(s);
    if (pathValued && opts.base && !["", "-", "disabled", "false"].includes(s) && !(0, import_node_path2.isAbsolute)(s) && !/^[a-z][a-z0-9+.-]*:\/\//i.test(s)) {
      s = (0, import_node_path2.resolve)(opts.base, s);
    }
    if (pathValued && opts.within) checkWithin(name, s, opts.within, opts.base ?? opts.cwd ?? process.cwd());
    return s;
  };
  for (const option of schema.options) {
    const found = pick(option);
    if (!found) continue;
    if (opts.controlled?.includes(option.name)) {
      out.controlled.push(found.key);
      continue;
    }
    if (found.value === null || found.value === void 0) continue;
    if (isBareFlag(option)) {
      const on = found.value === true || TRUE.test(String(found.value));
      out.argv.push(on ? `--${option.name}` : `--no-${option.name}`);
      continue;
    }
    if (opts.secretEnv && option.secret && !option.isArray) {
      out.env[option.variableName] = text(found.value, isPathValued(option.validation, option.type), `--${option.name}`);
      continue;
    }
    for (const item of Array.isArray(found.value) ? found.value : [found.value]) {
      out.argv.push(`--${option.name}`, text(item, isPathValued(option.validation, option.type), `--${option.name}`));
    }
  }
  const explicit = Array.isArray(opts.positionals) ? opts.positionals : void 0;
  const order = typeof opts.positionals === "string" ? opts.positionals : opts.positionalsOrder ?? "first";
  if (order !== "first" && order !== "last") throw new InputError("positionals order must be first or last");
  const positionals = [...explicit ?? []];
  if (!explicit) {
    let skipped = [];
    for (const argument of schema.arguments) {
      const found = pick(argument);
      if (!found || found.value === null || found.value === void 0) {
        skipped.push(argument);
        continue;
      }
      for (const gap of skipped) {
        if (!gap.default) throw new Error(`${argument.name} is given, so ${gap.name} must be too`);
        positionals.push(text(gap.default, false));
      }
      skipped = [];
      const values = Array.isArray(found.value) ? found.value : [found.value];
      positionals.push(...values.map((v) => text(v, isPathValued(argument.validation), argument.name)));
    }
  }
  if (positionals.some((p) => p.startsWith("-"))) out.argv.push("--", ...positionals);
  else if (order === "last") out.argv.push(...positionals);
  else out.argv.unshift(...positionals);
  out.unknown = Object.keys(input).filter((k) => !used.has(k));
  return out;
}
function realish(p) {
  let head = p;
  const tail2 = [];
  while (!(0, import_node_fs3.existsSync)(head) && (0, import_node_path2.dirname)(head) !== head) {
    tail2.unshift(head.slice((0, import_node_path2.dirname)(head).length).replace(/^[\\/]/, ""));
    head = (0, import_node_path2.dirname)(head);
  }
  return (0, import_node_path2.resolve)((0, import_node_fs3.existsSync)(head) ? (0, import_node_fs3.realpathSync)(head) : head, ...tail2);
}
function checkWithin(name, value, dirs, base) {
  if (["", "-", "disabled", "false"].includes(value)) return;
  if (/^[a-z][a-z0-9+.-]+:/i.test(value) && !(0, import_node_path2.isAbsolute)(value)) {
    throw new InputError(`${name}: ${value} is not a path inside the allowed directories`);
  }
  const target = realish((0, import_node_path2.resolve)(base, value));
  const inside = dirs.some((dir) => {
    const rel = (0, import_node_path2.relative)(realish((0, import_node_path2.resolve)(dir)), target);
    return rel === "" || !rel.startsWith("..") && !(0, import_node_path2.isAbsolute)(rel);
  });
  if (!inside) throw new InputError(`${name}: ${value} is outside the allowed directories`);
}
function redactArgv(schema, argv) {
  const secret = new Set(schema.options.filter((o) => o.secret).map((o) => `--${o.name}`));
  const out = [...argv];
  for (let i = 0; i < out.length; i++) {
    if (out[i] === "--") break;
    const eq = out[i].indexOf("=");
    if (eq > 0 && secret.has(out[i].slice(0, eq))) out[i] = `${out[i].slice(0, eq)}=***`;
    else if (secret.has(out[i]) && i + 1 < out.length) out[++i] = "***";
  }
  return out;
}

// packages/tools/src/run.ts
var import_node_child_process2 = require("node:child_process");
var import_node_stream = require("node:stream");
var import_node_string_decoder = require("node:string_decoder");
function start(file, argv, opts = {}) {
  const started = Date.now();
  const child = (0, import_node_child_process2.spawn)(file, argv, {
    cwd: opts.cwd,
    env: opts.env ?? process.env,
    stdio: [opts.stdin === void 0 ? "ignore" : "pipe", "pipe", "pipe"],
    signal: opts.signal
  });
  if (opts.stdin !== void 0 && child.stdin) {
    child.stdin.on("error", () => {
    });
    if (opts.stdin instanceof import_node_stream.Readable) opts.stdin.pipe(child.stdin);
    else child.stdin.end(opts.stdin);
  }
  const limit = opts.maxOutput || Infinity;
  let truncated = false;
  const collect = (stream, onChunk) => {
    const chunks = [];
    const decoder = new import_node_string_decoder.StringDecoder("utf8");
    let size = 0;
    stream.on("data", (chunk) => {
      if (onChunk) onChunk(decoder.write(chunk));
      if (size >= limit) return void (truncated = true);
      if (size + chunk.length > limit) {
        chunk = chunk.subarray(0, limit - size);
        truncated = true;
      }
      chunks.push(chunk);
      size += chunk.length;
    });
    return () => Buffer.concat(chunks);
  };
  const [childOut, childErr] = [child.stdout, child.stderr];
  const mode = opts.stdout ?? "text";
  const stdout = mode === "stream" ? () => Buffer.alloc(0) : collect(childOut, opts.onStdout);
  const stderr = collect(childErr, opts.onStderr);
  const result = new Promise((resolve3, reject) => {
    let timedOut = false;
    const timer = opts.timeoutMs ? setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, opts.timeoutMs) : void 0;
    child.on("error", (err) => {
      if (err.name === "AbortError") return;
      clearTimeout(timer);
      reject(err);
    });
    child.on("close", (exitCode, signal) => {
      clearTimeout(timer);
      const out = stdout();
      resolve3({
        command: [file, ...argv],
        exitCode,
        signal,
        timedOut,
        stdout: mode === "text" ? out.toString("utf8") : "",
        ...mode === "buffer" ? { stdoutBuffer: out } : {},
        stderr: stderr().toString("utf8"),
        ...truncated ? { truncated } : {},
        durationMs: Date.now() - started
      });
    });
  });
  return { child, stdout: childOut, result };
}
function run(file, argv, opts = {}) {
  if (opts.stdout === "stream") throw new Error("run() collects stdout; use start() for stdout: 'stream'");
  return start(file, argv, opts).result;
}
function tail(text, lines = 40) {
  return text.replace(/\x1b\[[0-9;]*m/g, "").split("\n").filter((l, i, all) => l || i < all.length - 1).slice(-lines);
}
function shellQuote(args) {
  return args.map((a) => /^[A-Za-z0-9_@%+=:,./-]+$/.test(a) ? a : `'${a.replace(/'/g, "'\\''")}'`).join(" ");
}

// packages/tools/src/json-schema.ts
var PATTERNS = {
  ip: "^([0-9]{1,3}\\.){3}[0-9]{1,3}$|^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}$",
  hostname: "^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
  url: "^https?://[a-zA-Z0-9.-]+(:[0-9]+)?(/.*)?$",
  email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
  uuid: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
  "date:YYYY-MM-DD": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
};
function bounds(spec, min, max) {
  const m = /^([0-9.]*)-([0-9.]*)$/.exec(spec);
  if (!m) return spec ? { [min]: Number(spec), [max]: Number(spec) } : {};
  return { ...m[1] ? { [min]: Number(m[1]) } : {}, ...m[2] ? { [max]: Number(m[2]) } : {} };
}
function valueSchema(validation, choices = []) {
  const [rule, spec = ""] = validation.split(/:(.*)/s);
  if (validation in PATTERNS) return { type: "string", pattern: PATTERNS[validation] };
  switch (rule) {
    case "int":
      return { type: "integer", ...bounds(spec, "minimum", "maximum") };
    case "float":
      return { type: "number", ...bounds(spec, "minimum", "maximum") };
    case "port":
      return { type: "integer", minimum: 1, maximum: 65535 };
    case "bool":
      return { type: "boolean" };
    case "string":
      return { type: "string", ...bounds(spec, "minLength", "maxLength") };
    case "choice":
      return { type: "string", enum: choices.length ? choices : spec.split(",") };
    case "regex":
      return { type: "string", pattern: spec };
    default:
      return { type: "string" };
  }
}
function typedDefault(value, schema) {
  if (schema.type === "integer" || schema.type === "number") return Number(value);
  if (schema.type === "boolean") return /^(true|1|yes|on)$/i.test(value);
  return value;
}
function property(item, many, flag) {
  const value = flag ? { type: "boolean" } : valueSchema(item.validation, "choices" in item ? item.choices : []);
  const out = many ? { type: "array", items: value } : { ...value };
  if (item.description) out.description = item.description;
  if (item.default !== "" && !many) out.default = typedDefault(item.default, value);
  if ("secret" in item && item.secret) Object.assign(out, { writeOnly: true, format: "password" });
  return out;
}
function toJsonSchema(schema) {
  const properties = {};
  const required = [];
  for (const argument of schema.arguments) {
    properties[inputKey(argument.name)] = property(argument, argument.isVariadic, false);
    if (argument.required) required.push(inputKey(argument.name));
  }
  for (const option of schema.options) {
    if (option.name === "help") continue;
    properties[inputKey(option.name)] = property(option, option.isArray, isBareFlag(option));
  }
  const given = (long) => {
    const option = schema.options.find((o) => o.name === long);
    if (option && isBareFlag(option)) return { const: true };
    return option?.isArray ? { type: "array", minItems: 1 } : { not: { type: "null" } };
  };
  const allOf = [];
  for (const c of schema.constraints ?? []) {
    if (c.type !== "exclusive") continue;
    for (let i = 0; i < c.options.length; i++) {
      for (let j = i + 1; j < c.options.length; j++) {
        const [a, b] = [c.options[i], c.options[j]];
        allOf.push({
          not: { required: [inputKey(a), inputKey(b)], properties: { [inputKey(a)]: given(a), [inputKey(b)]: given(b) } },
          description: `--${a} and --${b} cannot be used together`
        });
      }
    }
  }
  return {
    type: "object",
    ...schema.description ? { description: schema.description } : {},
    properties,
    ...required.length ? { required } : {},
    ...allOf.length ? { allOf } : {},
    additionalProperties: false
  };
}

// packages/tools/src/tools.ts
var import_node_fs4 = require("node:fs");
function globRegex(pattern) {
  const source = pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*|\*|\?/g, (m) => m === "**" ? ".*" : m === "*" ? "[^/]*" : "[^/]");
  return new RegExp(`^${source}$`);
}
function allowed(tool, filter) {
  const path = tool.words.join("/");
  if (filter.allow?.length && !filter.allow.some((p) => globRegex(p).test(path))) return false;
  if (filter.deny?.some((p) => globRegex(p).test(path))) return false;
  return !filter.readOnly || Boolean(tool.schema.effects?.includes("read-only"));
}
function expandCommands(cmd, schema) {
  const describe = (s) => s.description.split("\n")[0];
  if (!schema.commands?.length) return [{ ...cmd, schema, description: describe(schema) }];
  const out = [];
  const visit = (chain, words) => {
    const node = chain[chain.length - 1];
    if (node.commands?.length) {
      for (const child of node.commands) visit([...chain, child], [...words, child.name]);
      return;
    }
    const nearest = (pick, empty = () => false) => {
      for (let i = chain.length - 1; i >= 0; i--) {
        const v = pick(chain[i]);
        if (v !== void 0 && v !== null && !empty(v)) return v;
      }
      return void 0;
    };
    const flat = {
      clyops: schema.clyops,
      script: [schema.script, ...words].join(" "),
      description: node.description,
      epilog: node.epilog,
      arguments: node.arguments,
      options: [...chain].reverse().flatMap((s) => s.options),
      requiredCommands: chain.flatMap((s) => s.requiredCommands),
      effects: nearest((s) => s.effects, (v) => v.length === 0) ?? [],
      constraints: chain.flatMap((s) => s.constraints ?? []),
      stdin: nearest((s) => s.stdin) ?? null,
      stdout: nearest((s) => s.stdout) ?? null,
      commands: []
    };
    out.push({ ...cmd, name: words[words.length - 1], words: [...cmd.words, ...words], schema: flat, description: describe(node), subcommand: words });
  };
  visit([schema], []);
  return out;
}
async function loadTools(root, opts = {}) {
  const tree = discover(root, { name: opts.name });
  const loaded = await Promise.all(
    commands(tree).filter((cmd) => cmd.kind === "tool").map(async (cmd) => {
      try {
        return expandCommands(cmd, await loadSchema(cmd.file));
      } catch (err) {
        opts.onError?.(cmd, err);
        return [];
      }
    })
  );
  const settings = { allow: tree.allow, deny: tree.deny };
  const tools = loaded.flat().filter((t) => allowed(t, settings) && allowed(t, opts.filter ?? {}));
  return { tree, tools };
}
async function watchTools(root, opts = {}) {
  const load = () => loadTools(root, { name: opts.name, filter: opts.filter, onError: opts.onError });
  let loaded = await load();
  let timer;
  let running = Promise.resolve();
  const reload = () => {
    running = running.then(async () => {
      try {
        const next = await load();
        if (JSON.stringify(next) === JSON.stringify(loaded)) return;
        loaded = next;
        opts.onChange?.(loaded);
      } catch (err) {
        opts.onError?.(null, err);
      }
    });
  };
  const watcher = (0, import_node_fs4.watch)(loaded.tree.dir, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(reload, opts.debounceMs ?? 250);
  });
  return {
    current: () => loaded,
    close: () => {
      clearTimeout(timer);
      watcher.close();
    }
  };
}
function startTool(tool, input, opts = {}) {
  const { argv, env } = toArgv(tool.schema, input, { within: opts.within, cwd: opts.cwd, secretEnv: opts.secretsInEnv !== false, positionals: opts.positionalsOrder });
  const full = [...tool.subcommand ?? [], ...argv];
  const started = start(tool.file, full, { ...opts, env: Object.keys(env).length ? { ...opts.env ?? process.env, ...env } : opts.env });
  const command = [tool.file, ...redactArgv(tool.schema, full)];
  return { ...started, command, result: started.result.then((r) => ({ ...r, command })) };
}
async function runTool(tool, input, opts = {}) {
  if (opts.stdout === "stream") throw new Error("runTool() collects stdout; use startTool() for stdout: 'stream'");
  const result = await startTool(tool, input, opts).result;
  const out = { ...result, ok: result.exitCode === 0 };
  try {
    if (result.stdout.trim()) out.json = JSON.parse(result.stdout);
  } catch {
  }
  return out;
}

// packages/tools/src/serve.ts
var import_node_fs5 = require("node:fs");
function isTextType(contentType) {
  const type = (contentType ?? "").split(";")[0].trim().toLowerCase();
  return !type || type.startsWith("text/") || type === "application/json" || type.endsWith("+json") || type === "application/xml";
}
function auditLog(target) {
  return (entry) => {
    const line = `${JSON.stringify({ time: (/* @__PURE__ */ new Date()).toISOString(), ...entry })}
`;
    if (target === "-") process.stderr.write(line);
    else (0, import_node_fs5.appendFileSync)(target, line);
  };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  InputError,
  allowed,
  auditLog,
  checkWithin,
  classify,
  commandName,
  commands,
  discover,
  expandCommands,
  inputKey,
  inputKeys,
  isBareFlag,
  isPathValued,
  isTextType,
  loadSchema,
  loadTools,
  readSettings,
  redactArgv,
  run,
  runTool,
  shellQuote,
  stamp,
  start,
  startTool,
  tail,
  toArgv,
  toJsonSchema,
  valueSchema,
  watchTools
});
